//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Sensor.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_Sensor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CO2Level {
            get {
                return ResourceManager.GetString("CO2Level", resourceCulture);
            }
        }

        /// <summary>
        ///   During conditioning (about 22 seconds), CO2, temperature and humidity readings will all be unavailable. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmConditioningMsg {
            get {
                return ResourceManager.GetString("ConfirmConditioningMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Run CO2 Conditioning? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmConditioningTitle {
            get {
                return ResourceManager.GetString("ConfirmConditioningTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Reset the CO2 sensor to factory defaults? Auto-calibration will rebuild from fresh trend data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmFactoryResetMsg {
            get {
                return ResourceManager.GetString("ConfirmFactoryResetMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 Factory Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmFactoryResetTitle {
            get {
                return ResourceManager.GetString("ConfirmFactoryResetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Existing data will be cleared. Start new logging? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 conditioning complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditioningDone {
            get {
                return ResourceManager.GetString("ConditioningDone", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 conditioning started (about 22 seconds). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditioningStarted {
            get {
                return ResourceManager.GetString("ConditioningStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EndLogging {
            get {
                return ResourceManager.GetString("EndLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportMessage {
            get {
                return ResourceManager.GetString("ExportMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 sensor reset to factory defaults. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FactoryResetDone {
            get {
                return ResourceManager.GetString("FactoryResetDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Illuminance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGGING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingStatus {
            get {
                return ResourceManager.GetString("LoggingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 Conditioning (~22 s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaintConditioning {
            get {
                return ResourceManager.GetString("MaintConditioning", resourceCulture);
            }
        }

        /// <summary>
        ///   CO2 Factory Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaintFactoryReset {
            get {
                return ResourceManager.GetString("MaintFactoryReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Maintenance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Records に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Relative Humidity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Samples: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartLogging {
            get {
                return ResourceManager.GetString("StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Velocity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
